coverallsapp/github-action

- README.md
Fixed typo in default value for `path-to-lcov`
> Fixed Readme Typo

- README.md
There is no need to checkout the repository, install Node.js, and
run `npm install`.
> remove unneeded steps from parallel example

- README.md
- action.yml
- lib/run.js
- src/run.ts
This PR allows users to override both the commit and the branch name if they wish to do so.
In our use-case this allows us to use `pull_request_target` as a [trigger](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target) for GH actions.
> feat: add addition override parameters

- README.md
Because `GitHub Actions` is more understandable and correct.
> docs: Fix GitHub CI to GitHub Actions

- src/run.ts
Because `err` contains the actual error message. Moreover, `readFileSync` doesn't only fail if the file doesn't exists.
> fix: Throw read file sync error instead of throwing static error messages

- README.md
This returns a unique descriptive string for the job, making it
suitable for direct copy-paste for people who don't read the full text
here, or who manage lots of repos with different configurations and
want something that just works for all of them.
> docs: make flag-name unique for copy-paste from README

- dist/index.js
- src/run.ts
> fix: allow overwrite service_job_id

- action.yml
Precedent https://github.com/actions/checkout/blob/main/action.yml#L24
> fix: github-token default to `${{ github.token }}`

- README.md
> docs: add a note about v2

- README.md
- action.yml
> feat: add allow-empty option

- action.yml
Check the checksums when downloading binaries from Github releases.
> feat: check sha256sum

- README.md
- action.yml
- dist/index.js
- src/run.ts
**Summary**
Add `debug` option that enables debug logging
> feat: add debug option

- README.md
- action.yml
With `fail-on-error: false` you can skip upload and parsing errors of coverage reporter.
Available since `coverage-reporter 0.6.3`
> feat: add fail-on-error option

- action.yml
> feat: use pwsh for windows

- action.yml
**:wrench: Summary**
Use `-Force` flag to prevent an error
> fix: don't fail if bin directory exists on windows

- action.yml
This also removes the output section which is not being used for anything.
> Set default values as strings per GH Action requirements

- README.md
- action.yml
This add a `coverage-reporter-version` parameter that allows users to specify a version of [coverage-reporter](https://github.com/coverallsapp/coverage-reporter) to use. It will default to the latest version if not specified. This currently only works for Linux and Windows until versioning can be added to the Coveralls Homebrew tap.
> Allow pinning of coverage reporter version

- .github/workflows/test.yml
- action.yml
Parallel changes to the orb changes here: https://github.com/coverallsapp/orb/pull/46
Make sure the `fail-on-error` option's behavior also applies to failures of **setup tasks**, like: 
- Failure to download the binary; 
- Failure to verify the binary; and
- Failure to find the downloaded binary after extraction.
Rather than just to failures of the **coveralls commands**:
- `coveralls report`; or 
- `coveralls done`
> Extend behavior of `fail-on-error` option to setup failures

- README.md
prepend the `v`. I copied and pasted the example to my workflow, and then it took me quite a while to figure out the github action errors:
```
Error: Unable to resolve action `actions/checkout@4`, unable to find version `4`. Unable to resolve action `actions/setup-node@3`, unable to find version `3`
```
> docs: fix the action version

- .github/workflows/test.yml
- action.yml
Let users substitute an alternate **build number** for the _default_ build number: `S{{ github.run_id }} `.
- @brianatgather 🙏 
Please note that substituting key input values, like **build number** (aka. [service_number](https://docs.coveralls.io/api-jobs-endpoint#:~:text=String-,service_number,-The%20build%20number)), so they are passed to the `coverage-reporter` binary from this `github-action`, is always possible through the use of [Coveralls Environment Variables](https://github.com/coverallsapp/coverage-reporter/blob/master/doc/configuration.md#env-variables).
To substitute **build number**, use `COVERALLS_SERVICE_NUMBER` in your step config:
- **Example: commit sha**: - A common alternative to `${{ github.run_id }}` that can be used to tie _several_ GitHub Actions workflows together …
> Add build number to supported inputs options

- .github/workflows/test.yml
- action.yml
Fixes #225 
Verify that `coverage-reporter-version` input option is being recognized.
> Verify that `coverage-reporter-version` option is recognized

- .github/workflows/update-major-version-tag.yml
- #222 
Special thanks to @kurtmckee for guidance on the exact issue (and patience).
"Never again..."
> Always point the major version tag to the latest release

- .github/workflows/update-major-version-tag.yml
Follow-up on PR #230 
Add a couple of steps to `update-major-version-tag.yml` to: 
1. Reset the major version tag on the local runner in case it's needed for subsequent workflow steps anywhere else; and 
2. Display new details on the major version tag to verify it worked as expected and points to the latest release.
> Add a couple of helpful steps to update-major-version-tag workflow

- .github/workflows/test.yml
- action.yml
Fixes #218 
Since we have added support for `coverage-reporter` on `aarch64`, we need to provide users of our `github-action` the ability to select this architecture-specific version of `coverage-reporter` when on an `aarch64` / `arm64` runner.
> Add `coverage-reporter-platform` input option

- action.yml
This is a follow-up to #233 which partially fixed #218. This change removes the need for consumers to specify the platform. This makes this action easier to use within a matrix.
> Automatically detect the platform to install

- README.md
A few of the supported inputs were missing, most notably the recently added `coverage-reporter-platform` input (see #233).
Fixed now.
Includes fixing up a grammatical error.
> README/Inputs: list all (non-deprecated) inputs

- README.md
- action.yml
This is a follow-up to #238, where I introduced a feature to automatically detect the platform when none was specified. I failed to notice that there was a default value for the variable of "x86_64" set, which effectively made the code added in #238 useless. In this pull request, I'm setting the default value to `auto-detect` so that we can get the correct platform every time.
> Explicitly set auto-detect as default for platform
